[package]
name = "rust-ptouch-usb"
version = "0.1.0"
authors = ["yako"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.4"

